# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.swyftx import ImplicitAPI
from ccxt.base.types import Any, Balances, Currency, Int, Market, Str, Trade, Transaction
from typing import List
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import AuthenticationError
from ccxt.base.decimal_to_precision import TICK_SIZE


class swyftx(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(swyftx, self).describe(), {
            'id': 'swyftx',
            'name': 'Swyftx',
            'countries': ['AU'],  # Australia
            'rateLimit': 1000,
            'pro': False,
            'requiredCredentials': {
                'apiKey': True,
                'secret': False,  # Secret is optional - can be JWT or will be obtained via API key
            },
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'addMargin': False,
                'cancelOrder': False,
                'closeAllPositions': False,
                'closePosition': False,
                'createMarketOrder': False,
                'createOrder': False,
                'createReduceOnlyOrder': False,
                'createStopLimitOrder': False,
                'createStopMarketOrder': False,
                'createStopOrder': False,
                'fetchBalance': True,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchLeverage': False,
                'fetchLeverageTiers': False,
                'fetchMarginMode': False,
                'fetchMarkOHLCV': False,
                'fetchMyTrades': True,
                'fetchOpenInterestHistory': False,
                'fetchOrderBook': False,
                'fetchPosition': False,
                'fetchPositionHistory': False,
                'fetchPositionMode': False,
                'fetchPositions': False,
                'fetchPositionsForSymbol': False,
                'fetchPositionsHistory': False,
                'fetchPositionsRisk': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': False,
                'fetchTickers': False,
                'fetchTrades': False,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchTransactions': False,
                'reduceMargin': False,
                'setLeverage': False,
                'setMarginMode': False,
                'setPositionMode': False,
                'ws': False,
            },
            'urls': {
                'logo': 'https://swyftx.com.au/wp-content/uploads/2021/03/swyftx-logo.png',
                'api': {
                    'public': 'https://api.swyftx.com.au',
                    'private': 'https://api.swyftx.com.au',
                },
                'www': 'https://swyftx.com.au',
                'doc': 'https://docs.swyftx.com.au',
            },
            'api': {
                'public': {
                    'get': [
                        'markets/detail',
                    ],
                },
                'private': {
                    'get': [
                        'user/transactionReport',
                        'user/balance',
                    ],
                },
            },
            'fees': {
                'trading': {
                    'tierBased': False,
                    'percentage': True,
                    'maker': self.parse_number('0.006'),  # 0.6%
                    'taker': self.parse_number('0.006'),  # 0.6%
                },
            },
            'precisionMode': TICK_SIZE,
            'exceptions': {
                'exact': {},
                'broad': {},
            },
        })

    def refresh_access_token(self) -> str:
        # Swyftx requires exchanging API Key for JWT access token
        if not self.apiKey:
            raise AuthenticationError(self.id + ' refreshAccessToken() requires apiKey')
        url = self.urls['api']['private'] + '/auth/refresh/'
        body = self.json({'apiKey': self.apiKey})
        headers = {
            'Content-Type': 'application/json',
        }
        response = self.fetch(url, 'POST', headers, body)
        # Check for errors
        if response.error:
            errorCode = self.safe_string(response.error, 'error')
            errorMessage = self.safe_string(response.error, 'message', 'Unknown error')
            if errorCode == 'QueryError' or errorCode == 'AuthError':
                raise AuthenticationError(self.id + ' ' + errorMessage + '(invalid API key)')
            raise ExchangeError(self.id + ' ' + errorMessage)
        # Extract access token from response
        accessToken = self.safe_string(response, 'accessToken')
        if not accessToken:
            raise ExchangeError(self.id + ' refreshAccessToken() did not return an access token')
        # Cache the token(store in instance property)
        getattr(self, 'accessToken') = accessToken
        # JWT tokens from Swyftx typically expire in 24 hours
        # Set expiry to 23 hours from now to be safe
        getattr(self, 'tokenExpiry') = self.milliseconds() + (23 * 60 * 60 * 1000)
        return accessToken

    def ensure_access_token(self) -> str:
        # Check if we have a valid cached token
        now = self.milliseconds()
        if getattr(self, 'accessToken') and getattr(self, 'tokenExpiry') and now < getattr(self, 'tokenExpiry'):
            return getattr(self, 'accessToken')
        # If secret is provided directly(JWT), use that and cache it
        if self.secret and self.secret.startswith('eyJ'):
            getattr(self, 'accessToken') = self.secret
            getattr(self, 'tokenExpiry') = now + (23 * 60 * 60 * 1000)  # Cache for 23 hours
            return self.secret
        # Otherwise, refresh using API key
        return self.refresh_access_token()

    def sign(self, path: str, api: str = 'public', method: str = 'GET', params: Any = {}, headers: Any = None, body: Any = None) -> Any:
        url = self.urls['api'][api] + '/' + path
        if api == 'public':
            if params:
                url += '?' + self.urlencode(params)
        elif api == 'private':
            self.check_required_credentials()
            # Use cached access token if available, otherwise will be refreshed by fetch override
            token = getattr(self, 'accessToken') or self.secret or ''
            headers = {
                'Authorization': 'Bearer ' + token,
                'Content-Type': 'application/json',
            }
            if params:
                if method == 'GET':
                    url += '?' + self.urlencode(params)
                else:
                    body = self.json(params)
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    def fetch(self, url, method='GET', headers: Any = None, body: Any = None):
        # Ensure we have a valid access token before making private API calls
        if url.includes('/user/') or url.includes('/auth/'):
            # Skip token refresh for the refresh endpoint itself
            if not url.includes('/auth/refresh/'):
                self.ensure_access_token()
                # Update authorization header with fresh token
                if headers and headers['Authorization']:
                    headers['Authorization'] = 'Bearer ' + getattr(self, 'accessToken')
        return super(swyftx, self).fetch(url, method, headers, body)

    def fetch_my_trades(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        request: dict = {}
        # 'from' parameter is required by the API
        if since is not None:
            request['from'] = since
        else:
            # Default to 1 year ago if not specified
            request['from'] = Date.now() - (365 * 24 * 60 * 60 * 1000)
        # 'to' parameter is required by the API
        to = self.safe_integer(params, 'to')
        request['to'] = to if (to is not None) else Date.now()
        # Add 'offset' parameter for timezone offset
        request['offset'] = self.safe_integer(params, 'offset', 36000000)  # Default to Australian timezone
        # Add 'type' parameter(csv or pdf - API doesn't support json)
        request['type'] = self.safe_string(params, 'type', 'csv')
        response = self.privateGetUserTransactionReport(self.extend(request, params))
        # Parse CSV response
        if isinstance(response, str) and response.includes('Crypto Transactions'):
            csvTransactions = self.parse_swyftx_csv_transactions(response)
            # Return ALL transactions(both crypto trades and fiat deposits)
            return self.parse_trades(csvTransactions, None, since, limit)
        # Fallback for other response formats
        transactions = self.safe_value(response, 'data', [])
        return self.parse_trades(transactions, None, since, limit)

    def fetch_balance(self, params={}) -> Balances:
        self.load_markets()
        response = self.privateGetUserBalance(params)
        balances = self.safe_value(response, 'data', [])
        result: dict = {'info': response}
        for i in range(0, len(balances)):
            balance = balances[i]
            currencyId = self.safe_string(balance, 'asset')
            code = self.safe_currency_code(currencyId)
            account = self.account()
            account['free'] = self.safe_string(balance, 'availableAmount')
            account['used'] = self.safe_string(balance, 'lockedAmount')
            account['total'] = self.safe_string(balance, 'totalAmount')
            result[code] = account
        return self.safe_balance(result)

    def parse_trade(self, trade: dict, market: Market = None) -> Trade:
        # Handle CSV format from transaction report
        if self.safe_string(trade, '_section'):
            return self.parse_swyftx_csv_trade(trade, market)
        # Handle standard API format
        id = self.safe_string(trade, 'id')
        orderId = self.safe_string(trade, 'orderId')
        timestamp = self.parse8601(self.safe_string(trade, 'executedTime'))
        marketId = self.safe_string(trade, 'primary')
        symbol = self.safe_symbol(marketId, market)
        side = self.safe_string_lower(trade, 'side')
        amount = self.safe_string(trade, 'amount')
        price = self.safe_string(trade, 'rate')
        cost = self.safe_string(trade, 'total')
        fee = {
            'cost': self.safe_string(trade, 'fee'),
            'currency': self.safe_string(trade, 'feeCurrency'),
        }
        return self.safe_trade({
            'id': id,
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'order': orderId,
            'type': None,
            'side': side,
            'amount': amount,
            'price': price,
            'cost': cost,
            'fee': fee,
        }, market)

    def parse_swyftx_csv_trade(self, trade: dict, market: Market = None) -> Trade:
        # Parse Swyftx CSV format for both trades and deposits/withdrawals
        dateStr = self.safe_string(trade, 'Date')
        timeStr = self.safe_string(trade, 'Time')
        event = self.safe_string(trade, 'Event')
        asset = self.safe_string(trade, 'Asset')
        amount = self.safe_string(trade, 'Amount')
        paidCurrency = self.safe_string(trade, 'Currency')
        paidValue = self.safe_string(trade, 'Value')
        rate = self.safe_string(trade, 'Rate')
        uuid = self.safe_string(trade, 'UUID')
        txId = self.safe_string(trade, 'Transaction ID')
        feeAmount = self.safe_string(trade, 'Fee Amount')
        feeAsset = self.safe_string(trade, 'Fee Asset')
        section = self.safe_string(trade, '_section')
        # Parse datetime from DD/MM/YYYY HH:MM:SS format
        timestamp = None
        if dateStr and timeStr:
            day, month, year = dateStr.split('/')
            datetime = `${year}-${month.rjust(2, '0')}-${day.rjust(2, '0')}T${timeStr}`
            timestamp = self.parse8601(datetime)
        # Handle different transaction types
        symbol = None
        side = None
        type = None
        price = None
        cost = None
        if section == 'Crypto Transactions':
            # Crypto trading transactions
            if paidCurrency == 'AUD':
                symbol = asset + '/AUD'
            elif paidCurrency and paidCurrency != asset:
                symbol = asset + '/' + paidCurrency
            if event == 'buy':
                side = 'buy'
            elif event == 'sell':
                side = 'sell'
            type = 'market'
            price = self.parse_number(rate)
            cost = self.parse_number(paidValue)
        elif section == 'Fiat Transactions':
            # Fiat deposits/withdrawals - represent for consistency
            symbol = asset + '/AUD'  # AUD deposits/withdrawals
            if event == 'deposit':
                side = 'buy'
            elif event == 'withdrawal':
                side = 'sell'
            type = event  # 'deposit' or 'withdrawal'
            price = 1  # 1:1 for fiat
            cost = self.parse_number(amount)  # Amount is the cost for fiat
        return self.safe_trade({
            'id': uuid or txId,
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'order': None,
            'type': type,
            'side': side,
            'amount': self.parse_number(amount),
            'price': price,
            'cost': cost,
            'fee': {
                'cost': self.parse_number(feeAmount),
                'currency': feeAsset or asset,
            },
        }, market)

    def parse_transaction(self, transaction: dict, currency: Currency = None) -> Transaction:
        # Handle CSV format from transaction report
        if self.safe_string(transaction, '_section'):
            return self.parse_swyftx_csv_transaction(transaction, currency)
        # Handle standard API format
        id = self.safe_string(transaction, 'id')
        timestamp = self.parse8601(self.safe_string(transaction, 'createdTime'))
        currencyId = self.safe_string(transaction, 'asset')
        code = self.safe_currency_code(currencyId, currency)
        amount = self.safe_string(transaction, 'amount')
        type = self.safe_string_lower(transaction, 'type')
        status = self.parse_transaction_status(self.safe_string(transaction, 'status'))
        return {
            'info': transaction,
            'id': id,
            'currency': code,
            'amount': self.parse_number(amount),
            'network': None,
            'address': None,
            'addressTo': None,
            'addressFrom': None,
            'tag': None,
            'tagTo': None,
            'tagFrom': None,
            'status': status,
            'type': type,
            'updated': None,
            'txid': self.safe_string(transaction, 'txid'),
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'fee': {
                'currency': code,
                'cost': self.parse_number(self.safe_string(transaction, 'fee')),
            },
            'comment': None,
            'internal': False,
        }

    def parse_swyftx_csv_transaction(self, transaction: dict, currency: Currency = None) -> Transaction:
        # Parse Swyftx CSV format: Date,Time,Event,Asset,Amount,Currency,Value,Rate,AUD Value Fee,AUD Value,Fee Amount,Fee Asset...
        dateStr = self.safe_string(transaction, 'Date')
        timeStr = self.safe_string(transaction, 'Time')
        event = self.safe_string(transaction, 'Event')
        asset = self.safe_string(transaction, 'Asset')
        amount = self.safe_string(transaction, 'Amount')
        paidCurrency = self.safe_string(transaction, 'Currency')  # What was paid(BTC in ETH/BTC trade)
        paidValue = self.safe_string(transaction, 'Value')  # How much was paid
        txId = self.safe_string(transaction, 'Transaction ID')
        uuid = self.safe_string(transaction, 'UUID')
        feeAmount = self.safe_string(transaction, 'Fee Amount')
        feeAsset = self.safe_string(transaction, 'Fee Asset')
        # Parse datetime from DD/MM/YYYY HH:MM:SS format
        timestamp = None
        if dateStr and timeStr:
            day, month, year = dateStr.split('/')
            datetime = `${year}-${month.rjust(2, '0')}-${day.rjust(2, '0')}T${timeStr}`
            timestamp = self.parse8601(datetime)
        code = self.safe_currency_code(asset, currency)
        # Map Swyftx events to CCXT transaction types
        type = event
        if event == 'buy' or event == 'sell':
            type = 'trade'
        elif event == 'deposit':
            type = 'deposit'
        elif event == 'withdrawal':
            type = 'withdrawal'
        # Add trading pair information for crypto-to-crypto trades
        comment = None
        if paidCurrency and paidCurrency != 'AUD' and paidCurrency != asset:
            comment = `${event} ${asset} with ${paidValue} ${paidCurrency}`
        return {
            'info': transaction,
            'id': uuid or txId,
            'currency': code,
            'amount': self.parse_number(amount),
            'network': None,
            'address': None,
            'addressTo': None,
            'addressFrom': None,
            'tag': None,
            'tagTo': None,
            'tagFrom': None,
            'status': 'ok',  # CSV transactions are typically completed
            'type': type,
            'updated': None,
            'txid': txId,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'fee': {
                'currency': feeAsset or code,
                'cost': self.parse_number(feeAmount),
            },
            'comment': comment,
            'internal': False,
        }

    def parse_transaction_status(self, status: Str) -> str:
        statuses: dict = {
            'completed': 'ok',
            'pending': 'pending',
            'failed': 'failed',
            'cancelled': 'canceled',
        }
        return self.safe_string(statuses, status, status)

    def parse_swyftx_csv_transactions(self, csvText: str) -> List[Any]:
        transactions = []
        lines = csvText.split('\n')
        currentSection = ''
        headers = []
        for i in range(0, len(lines)):
            line = lines[i].strip()
            if line == 'Crypto Transactions' or line == 'Fiat Transactions':
                currentSection = line
                # Next line should be headers
                if i + 1 < len(lines):
                    headers = lines[i + 1].split(',')
                i++  # Skip the header line
                continue
            # Skip empty lines, section headers, and subtotals
            if not line or line.includes('sub total') or line.includes('Summary') or line.includes('no positions'):
                continue
            # Parse transaction data
            if currentSection and len(headers) > 0 and line.includes(','):
                values = self.parse_csv_line(line)  # Use proper CSV parsing
                if len(values) >= 3 and values[0] and values[1] and values[2]:  # Must have date, time, and event
                    transaction: dict = {}
                    for j in range(0, min(len(headers), len(values))):
                        header = headers[j].strip()
                        value = values[j].strip()
                        if header:
                            transaction[header] = value
                    transaction['_section'] = currentSection
                    transactions.append(transaction)
        return transactions

    def parse_csv_line(self, line: str) -> List[str]:
        # Simple CSV parser that handles basic comma-separated values
        # This can be improved for more complex CSV with quoted fields if needed
        return line.split(',').map((field) => field.strip())

    def handle_errors(self, code: Int, reason: str, url: str, method: str, headers: dict, body: str, response: Any, requestHeaders: Any, requestBody: Any) -> Any:
        if response is None:
            return None
        success = self.safe_value(response, 'success')
        if success == False:
            message = self.safe_string(response, 'message', body)
            errorCode = self.safe_string(response, 'error')
            if errorCode == 'UNAUTHORIZED':
                raise AuthenticationError(self.id + ' ' + message)
            raise ExchangeError(self.id + ' ' + message)
        return None
