// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class swyftx : Exchange
{
    public swyftx (object args = null): base(args) {}

    public async Task<object> publicGetMarketsDetail (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketsDetail",parameters);
    }

    public async Task<object> privateGetMarkets (object parameters = null)
    {
        return await this.callAsync ("privateGetMarkets",parameters);
    }

    public async Task<object> privateGetUserTrades (object parameters = null)
    {
        return await this.callAsync ("privateGetUserTrades",parameters);
    }

    public async Task<object> privateGetUserTransactionReport (object parameters = null)
    {
        return await this.callAsync ("privateGetUserTransactionReport",parameters);
    }

    public async Task<object> privateGetUserBalance (object parameters = null)
    {
        return await this.callAsync ("privateGetUserBalance",parameters);
    }

}