<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class swyftx extends \ccxt\async\Exchange {
    public function public_get_markets_detail($params = array()) {
        return $this->request('markets/detail', 'public', 'GET', $params, null, null, array());
    }
    public function private_get_user_transactionreport($params = array()) {
        return $this->request('user/transactionReport', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_user_balance($params = array()) {
        return $this->request('user/balance', 'private', 'GET', $params, null, null, array());
    }
    public function publicGetMarketsDetail($params = array()) {
        return $this->request('markets/detail', 'public', 'GET', $params, null, null, array());
    }
    public function privateGetUserTransactionReport($params = array()) {
        return $this->request('user/transactionReport', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUserBalance($params = array()) {
        return $this->request('user/balance', 'private', 'GET', $params, null, null, array());
    }
}
