<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\swyftx as Exchange;

class swyftx extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'swyftx',
            'name' => 'Swyftx',
            'countries' => array( 'AU' ), // Australia
            'rateLimit' => 1000,
            'pro' => false,
            'requiredCredentials' => array(
                'apiKey' => true,
                'secret' => false, // Secret is optional - can be JWT or will be obtained via API key
            ),
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'addMargin' => false,
                'cancelOrder' => false,
                'closeAllPositions' => false,
                'closePosition' => false,
                'createMarketOrder' => false,
                'createOrder' => false,
                'createReduceOnlyOrder' => false,
                'createStopLimitOrder' => false,
                'createStopMarketOrder' => false,
                'createStopOrder' => false,
                'fetchBalance' => true,
                'fetchBorrowRateHistories' => false,
                'fetchBorrowRateHistory' => false,
                'fetchCrossBorrowRate' => false,
                'fetchCrossBorrowRates' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchIsolatedBorrowRate' => false,
                'fetchIsolatedBorrowRates' => false,
                'fetchLeverage' => false,
                'fetchLeverageTiers' => false,
                'fetchMarginMode' => false,
                'fetchMarkOHLCV' => false,
                'fetchMyTrades' => true,
                'fetchOpenInterestHistory' => false,
                'fetchOrderBook' => false,
                'fetchPosition' => false,
                'fetchPositionHistory' => false,
                'fetchPositionMode' => false,
                'fetchPositions' => false,
                'fetchPositionsForSymbol' => false,
                'fetchPositionsHistory' => false,
                'fetchPositionsRisk' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => false,
                'fetchTickers' => false,
                'fetchTrades' => false,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
                'fetchTransactions' => false,
                'reduceMargin' => false,
                'setLeverage' => false,
                'setMarginMode' => false,
                'setPositionMode' => false,
                'ws' => false,
            ),
            'urls' => array(
                'logo' => 'https://swyftx.com.au/wp-content/uploads/2021/03/swyftx-logo.png',
                'api' => array(
                    'public' => 'https://api.swyftx.com.au',
                    'private' => 'https://api.swyftx.com.au',
                ),
                'www' => 'https://swyftx.com.au',
                'doc' => 'https://docs.swyftx.com.au',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'markets/detail',
                    ),
                ),
                'private' => array(
                    'get' => array(
                        'user/transactionReport',
                        'user/balance',
                    ),
                ),
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'maker' => $this->parse_number('0.006'), // 0.6%
                    'taker' => $this->parse_number('0.006'), // 0.6%
                ),
            ),
            'precisionMode' => TICK_SIZE,
            'exceptions' => array(
                'exact' => array(),
                'broad' => array(),
            ),
        ));
    }

    public function refresh_access_token(): string {
        // Swyftx requires exchanging API Key for JWT access token
        if (!$this->apiKey) {
            throw new AuthenticationError($this->id . ' refreshAccessToken() requires apiKey');
        }
        $url = $this->urls['api']['private'] . '/auth/refresh/';
        $body = $this->json(array( 'apiKey' => $this->apiKey ));
        $headers = array(
            'Content-Type' => 'application/json',
        );
        $response = $this->fetch($url, 'POST', $headers, $body);
        // Check for errors
        if ($response->error) {
            $errorCode = $this->safe_string($response->error, 'error');
            $errorMessage = $this->safe_string($response->error, 'message', 'Unknown error');
            if ($errorCode === 'QueryError' || $errorCode === 'AuthError') {
                throw new AuthenticationError($this->id . ' ' . $errorMessage . ' (invalid API key)');
            }
            throw new ExchangeError($this->id . ' ' . $errorMessage);
        }
        // Extract access token from $response
        $accessToken = $this->safe_string($response, 'accessToken');
        if (!$accessToken) {
            throw new ExchangeError($this->id . ' refreshAccessToken() did not return an access token');
        }
        // Cache the token (is_array(instance property) && array_key_exists(store, instance property))
        $this->$'accessToken' = $accessToken;
        // JWT tokens from Swyftx typically expire in 24 hours
        // Set expiry to 23 hours from now to be safe
        $this->$'tokenExpiry' = $this->milliseconds() . (23 * 60 * 60 * 1000);
        return $accessToken;
    }

    public function ensure_access_token(): string {
        // Check if we have a valid cached token
        $now = $this->milliseconds();
        if ($this->$'accessToken' && $this->$'tokenExpiry' && $now < $this->$'tokenExpiry') {
            return $this->$'accessToken';
        }
        // If secret is provided directly (JWT), use that and cache it
        if ($this->secret && str_starts_with($this->secret, 'eyJ')) {
            $this->$'accessToken' = $this->secret;
            $this->$'tokenExpiry' = $now . (23 * 60 * 60 * 1000); // Cache for 23 hours
            return $this->secret;
        }
        // Otherwise, refresh using API key
        return $this->refresh_access_token();
    }

    public function sign(string $path, string $api = 'public', string $method = 'GET', mixed $params = array (), mixed $headers = null, mixed $body = null): mixed {
        $url = $this->urls['api'][$api] . '/' . $path;
        if ($api === 'public') {
            if ($params) {
                $url .= '?' . $this->urlencode($params);
            }
        } elseif ($api === 'private') {
            $this->check_required_credentials();
            // Use cached access $token if available, otherwise will be refreshed by fetch override
            $token = $this->$'accessToken' || $this->secret || '';
            $headers = array(
                'Authorization' => 'Bearer ' . $token,
                'Content-Type' => 'application/json',
            );
            if ($params) {
                if ($method === 'GET') {
                    $url .= '?' . $this->urlencode($params);
                } else {
                    $body = $this->json($params);
                }
            }
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function fetch($url, $method = 'GET', mixed $headers = null, mixed $body = null) {
        // Ensure we have a valid access token before making private API calls
        if ($url->includes ('/user/') || $url->includes ('/auth/')) {
            // Skip token refresh for the refresh endpoint itself
            if (!$url->includes ('/auth/refresh/')) {
                $this->ensure_access_token();
                // Update authorization header with fresh token
                if ($headers && $headers['Authorization']) {
                    $headers['Authorization'] = 'Bearer ' . $this->$'accessToken';
                }
            }
        }
        return parent::fetch($url, $method, $headers, $body);
    }

    public function fetch_my_trades(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        $request = array();
        // 'from' parameter is required by the API
        if ($since !== null) {
            $request['from'] = $since;
        } else {
            // Default $to 1 year ago if not specified
            $request['from'] = Date.now () - (365 * 24 * 60 * 60 * 1000);
        }
        // 'to' parameter is required by the API
        $to = $this->safe_integer($params, 'to');
        $request['to'] = ($to !== null) ? $to : Date.now ();
        // Add 'offset' parameter for timezone offset
        $request['offset'] = $this->safe_integer($params, 'offset', 36000000); // Default $to Australian timezone
        // Add 'type' parameter (csv or pdf - API doesn't support json)
        $request['type'] = $this->safe_string($params, 'type', 'csv');
        $response = $this->privateGetUserTransactionReport ($this->extend($request, $params));
        // Parse CSV $response
        if (gettype($response) === 'string' && $response->includes ('Crypto Transactions')) {
            $csvTransactions = $this->parse_swyftx_csv_transactions($response);
            // Return ALL $transactions (both crypto trades and fiat deposits)
            return $this->parse_trades($csvTransactions, null, $since, $limit);
        }
        // Fallback for other $response formats
        $transactions = $this->safe_value($response, 'data', array());
        return $this->parse_trades($transactions, null, $since, $limit);
    }

    public function fetch_balance($params = array ()): array {
        $this->load_markets();
        $response = $this->privateGetUserBalance ($params);
        $balances = $this->safe_value($response, 'data', array());
        $result = array( 'info' => $response );
        for ($i = 0; $i < count($balances); $i++) {
            $balance = $balances[$i];
            $currencyId = $this->safe_string($balance, 'asset');
            $code = $this->safe_currency_code($currencyId);
            $account = $this->account();
            $account['free'] = $this->safe_string($balance, 'availableAmount');
            $account['used'] = $this->safe_string($balance, 'lockedAmount');
            $account['total'] = $this->safe_string($balance, 'totalAmount');
            $result[$code] = $account;
        }
        return $this->safe_balance($result);
    }

    public function parse_trade(array $trade, ?array $market = null): array {
        // Handle CSV format from transaction report
        if ($this->safe_string($trade, '_section')) {
            return $this->parse_swyftx_csv_trade($trade, $market);
        }
        // Handle standard API format
        $id = $this->safe_string($trade, 'id');
        $orderId = $this->safe_string($trade, 'orderId');
        $timestamp = $this->parse8601($this->safe_string($trade, 'executedTime'));
        $marketId = $this->safe_string($trade, 'primary');
        $symbol = $this->safe_symbol($marketId, $market);
        $side = $this->safe_string_lower($trade, 'side');
        $amount = $this->safe_string($trade, 'amount');
        $price = $this->safe_string($trade, 'rate');
        $cost = $this->safe_string($trade, 'total');
        $fee = array(
            'cost' => $this->safe_string($trade, 'fee'),
            'currency' => $this->safe_string($trade, 'feeCurrency'),
        );
        return $this->safe_trade(array(
            'id' => $id,
            'info' => $trade,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $symbol,
            'order' => $orderId,
            'type' => null,
            'side' => $side,
            'amount' => $amount,
            'price' => $price,
            'cost' => $cost,
            'fee' => $fee,
        ), $market);
    }

    public function parse_swyftx_csv_trade(array $trade, ?array $market = null): array {
        // Parse Swyftx CSV format for both trades and deposits/withdrawals
        $dateStr = $this->safe_string($trade, 'Date');
        $timeStr = $this->safe_string($trade, 'Time');
        $event = $this->safe_string($trade, 'Event');
        $asset = $this->safe_string($trade, 'Asset');
        $amount = $this->safe_string($trade, 'Amount');
        $paidCurrency = $this->safe_string($trade, 'Currency');
        $paidValue = $this->safe_string($trade, 'Value');
        $rate = $this->safe_string($trade, 'Rate');
        $uuid = $this->safe_string($trade, 'UUID');
        $txId = $this->safe_string($trade, 'Transaction ID');
        $feeAmount = $this->safe_string($trade, 'Fee Amount');
        $feeAsset = $this->safe_string($trade, 'Fee Asset');
        $section = $this->safe_string($trade, '_section');
        // Parse $datetime from DD/MM/YYYY HH:MM:SS format
        $timestamp = null;
        if ($dateStr && $timeStr) {
            list($day, $month, $year) = explode('/', $dateStr);
            $datetime = `${$year}-$array(str_pad($month, 2, '0', STR_PAD_LEFT))-$array(str_pad($day, 2, '0', STR_PAD_LEFT))T${$timeStr}`;
            $timestamp = $this->parse8601($datetime);
        }
        // Handle different transaction types
        $symbol = null;
        $side = null;
        $type = null;
        $price = null;
        $cost = null;
        if ($section === 'Crypto Transactions') {
            // Crypto trading transactions
            if ($paidCurrency === 'AUD') {
                $symbol = $asset . '/AUD';
            } elseif ($paidCurrency && $paidCurrency !== $asset) {
                $symbol = $asset . '/' . $paidCurrency;
            }
            if ($event === 'buy') {
                $side = 'buy';
            } elseif ($event === 'sell') {
                $side = 'sell';
            }
            $type = 'market';
            $price = $this->parse_number($rate);
            $cost = $this->parse_number($paidValue);
        } elseif ($section === 'Fiat Transactions') {
            // Fiat deposits/withdrawals - represent for consistency
            $symbol = $asset . '/AUD'; // AUD deposits/withdrawals
            if ($event === 'deposit') {
                $side = 'buy';
            } elseif ($event === 'withdrawal') {
                $side = 'sell';
            }
            $type = $event; // 'deposit' or 'withdrawal'
            $price = 1; // 1:1 for fiat
            $cost = $this->parse_number($amount); // Amount is the $cost for fiat
        }
        return $this->safe_trade(array(
            'id' => $uuid || $txId,
            'info' => $trade,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $symbol,
            'order' => null,
            'type' => $type,
            'side' => $side,
            'amount' => $this->parse_number($amount),
            'price' => $price,
            'cost' => $cost,
            'fee' => array(
                'cost' => $this->parse_number($feeAmount),
                'currency' => $feeAsset || $asset,
            ),
        ), $market);
    }

    public function parse_transaction(array $transaction, ?array $currency = null): array {
        // Handle CSV format from $transaction report
        if ($this->safe_string($transaction, '_section')) {
            return $this->parse_swyftx_csv_transaction($transaction, $currency);
        }
        // Handle standard API format
        $id = $this->safe_string($transaction, 'id');
        $timestamp = $this->parse8601($this->safe_string($transaction, 'createdTime'));
        $currencyId = $this->safe_string($transaction, 'asset');
        $code = $this->safe_currency_code($currencyId, $currency);
        $amount = $this->safe_string($transaction, 'amount');
        $type = $this->safe_string_lower($transaction, 'type');
        $status = $this->parse_transaction_status($this->safe_string($transaction, 'status'));
        return array(
            'info' => $transaction,
            'id' => $id,
            'currency' => $code,
            'amount' => $this->parse_number($amount),
            'network' => null,
            'address' => null,
            'addressTo' => null,
            'addressFrom' => null,
            'tag' => null,
            'tagTo' => null,
            'tagFrom' => null,
            'status' => $status,
            'type' => $type,
            'updated' => null,
            'txid' => $this->safe_string($transaction, 'txid'),
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'fee' => array(
                'currency' => $code,
                'cost' => $this->parse_number($this->safe_string($transaction, 'fee')),
            ),
            'comment' => null,
            'internal' => false,
        );
    }

    public function parse_swyftx_csv_transaction(array $transaction, ?array $currency = null): array {
        // Parse Swyftx CSV format => Date,Time,Event,Asset,Amount,Currency,Value,Rate,AUD Value Fee,AUD Value,Fee Amount,Fee Asset...
        $dateStr = $this->safe_string($transaction, 'Date');
        $timeStr = $this->safe_string($transaction, 'Time');
        $event = $this->safe_string($transaction, 'Event');
        $asset = $this->safe_string($transaction, 'Asset');
        $amount = $this->safe_string($transaction, 'Amount');
        $paidCurrency = $this->safe_string($transaction, 'Currency'); // What was paid (is_array(ETH/BTC trade) && array_key_exists(BTC, ETH/BTC trade))
        $paidValue = $this->safe_string($transaction, 'Value'); // How much was paid
        $txId = $this->safe_string($transaction, 'Transaction ID');
        $uuid = $this->safe_string($transaction, 'UUID');
        $feeAmount = $this->safe_string($transaction, 'Fee Amount');
        $feeAsset = $this->safe_string($transaction, 'Fee Asset');
        // Parse $datetime from DD/MM/YYYY HH:MM:SS format
        $timestamp = null;
        if ($dateStr && $timeStr) {
            list($day, $month, $year) = explode('/', $dateStr);
            $datetime = `${$year}-$array(str_pad($month, 2, '0', STR_PAD_LEFT))-$array(str_pad($day, 2, '0', STR_PAD_LEFT))T${$timeStr}`;
            $timestamp = $this->parse8601($datetime);
        }
        $code = $this->safe_currency_code($asset, $currency);
        // Map Swyftx events to CCXT $transaction types
        $type = $event;
        if ($event === 'buy' || $event === 'sell') {
            $type = 'trade';
        } elseif ($event === 'deposit') {
            $type = 'deposit';
        } elseif ($event === 'withdrawal') {
            $type = 'withdrawal';
        }
        // Add trading pair information for crypto-to-crypto trades
        $comment = null;
        if ($paidCurrency && $paidCurrency !== 'AUD' && $paidCurrency !== $asset) {
            $comment = `${$event} ${$asset} with ${$paidValue} ${$paidCurrency}`;
        }
        return array(
            'info' => $transaction,
            'id' => $uuid || $txId,
            'currency' => $code,
            'amount' => $this->parse_number($amount),
            'network' => null,
            'address' => null,
            'addressTo' => null,
            'addressFrom' => null,
            'tag' => null,
            'tagTo' => null,
            'tagFrom' => null,
            'status' => 'ok', // CSV transactions are typically completed
            'type' => $type,
            'updated' => null,
            'txid' => $txId,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'fee' => array(
                'currency' => $feeAsset || $code,
                'cost' => $this->parse_number($feeAmount),
            ),
            'comment' => $comment,
            'internal' => false,
        );
    }

    public function parse_transaction_status(?string $status): string {
        $statuses = array(
            'completed' => 'ok',
            'pending' => 'pending',
            'failed' => 'failed',
            'cancelled' => 'canceled',
        );
        return $this->safe_string($statuses, $status, $status);
    }

    public function parse_swyftx_csv_transactions(string $csvText): array {
        $transactions = array();
        $lines = explode('\n', $csvText);
        $currentSection = '';
        $headers = array();
        for ($i = 0; $i < count($lines); $i++) {
            $line = trim($lines[$i]);
            if ($line === 'Crypto Transactions' || $line === 'Fiat Transactions') {
                $currentSection = $line;
                // Next $line should be $headers
                if ($i + 1 < strlen($lines)) {
                    $headers = $lines[$i + explode(',', 1]);
                }
                $i++; // Skip the $header $line
                continue;
            }
            // Skip empty $lines, section $headers, and subtotals
            if (!$line || $line->includes ('sub total') || $line->includes ('Summary') || $line->includes ('no positions')) {
                continue;
            }
            // Parse $transaction data
            if ($currentSection && strlen($headers) > 0 && $line->includes (',')) {
                $values = $this->parse_csv_line($line); // Use proper CSV parsing
                if (strlen($values) >= 3 && $values[0] && $values[1] && $values[2]) { // Must have date, time, and event
                    $transaction = array();
                    for ($j = 0; $j < min (strlen($headers), strlen($values)); $j++) {
                        $header = trim($headers[$j]);
                        $value = trim($values[$j]);
                        if ($header) {
                            $transaction[$header] = $value;
                        }
                    }
                    $transaction['_section'] = $currentSection;
                    $transactions[] = $transaction;
                }
            }
        }
        return $transactions;
    }

    public function parse_csv_line(string $line): array {
        // Simple CSV parser that handles basic comma-separated values
        // This can be improved for more complex CSV with quoted fields if needed
        return explode(',', $line).map ((field) => trim(field));
    }

    public function handle_errors(?int $code, string $reason, string $url, string $method, array $headers, string $body, mixed $response, mixed $requestHeaders, mixed $requestBody): mixed {
        if ($response === null) {
            return null;
        }
        $success = $this->safe_value($response, 'success');
        if ($success === false) {
            $message = $this->safe_string($response, 'message', $body);
            $errorCode = $this->safe_string($response, 'error');
            if ($errorCode === 'UNAUTHORIZED') {
                throw new AuthenticationError($this->id . ' ' . $message);
            }
            throw new ExchangeError($this->id . ' ' . $message);
        }
        return null;
    }
}
